apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  labels:
    run: nginx-test
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: nginx-test
  externalIPs:
  - 192.168.1.10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
spec:
  selector:
    matchLabels:
      run: nginx-test
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx-test
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      containers:
      - name: nginx
        image: nginx:1.14.2
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
          readOnly: true
        ports:
        - containerPort: 80
